# Numpy 기초

파이썬 데이터 분석의 3대 라이브러리: 
* Numpy : 배열, 행열을 다룸
* Pandas : 엑셀와 같은 데이터프레임을 다룸
* Matplotlib : 시각화

https://numpy.org/


In [0]:
# numpy 라이브러리 임포트(불러오기)
import numpy as np

In [0]:
# 2. Array 정의 및 사용하기
# 리스트와 어레이(배열)의 차이
data1=[1,2,3,4,5]
data1

[1, 2, 3, 4, 5]

In [0]:
data2=[1,2,3,4,5]

In [0]:
# Numpy를 이용하여 array 정의하기
# 2-1. 위에서 만든 python list를 이용
arr1=np.array(data1)
print(arr1)

[1 2 3 4 5]


In [0]:
# array의 형태(크기) 확인
arr1.shape

(5,)

In [0]:
a=np.array([[1,2,3],[1[2]]])


TypeError: ignored

In [0]:
# 2-2. 바로 python list를 넣어 줌으로써 만들기
arr2=np.array([1,2,3,4,5])
print(arr2)

[1 2 3 4 5]


In [0]:
# 크기 찍어보기
arr2.shape

(5,)

In [0]:
# array의 자료형을 확인
arr2.dtype

dtype('int64')

In [0]:
data2=[1,2,3.5,6]
arr2=np.array(data2)
print(arr2.dtype)
print(arr2.shape)
print(arr2)


float64
(4,)
[1.  2.  3.5 6. ]


In [0]:
data2

[1, 2, 3.5, 6]

In [0]:
arr44=np.array([[1,2,3],[4,5,6],[10,33,12]])

arr44.shape

(3, 3)

In [0]:
arr4=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

arr4.shape


(4, 3)

In [0]:
arr4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

#### numpy shape
<pre>
numpy에서는 해당 array의 크기를 알 수 있다.
shape 을 확인함으로써 몇 개의 데이터가 있는지, 몇 차원으로 존재하는지 등을 확인할 수 있다.
위에서 arr1.shape의 결과는 (5,)으로써, 1차원의 데이터이며 총 5라는 크기를 갖고 있음을 알 수 있다.
arr4.shape의 결과는 (4,3)으로써, 2차원의 데이터이며 4*3 크기를 갖고 있는 array이다.
</pre>

#### numpy 자료형
<pre>
arr1이나 arr2는 int라는 자료형을 갖는 것에 반해 arr3는 float64라는 자료형을 갖는다.
이는 arr3 내부 데이터를 살펴보면 3.5라는 실수형 데이터를 갖기 때문임을 알 수 있다.
numpy에서 사용되는 자료형은 아래와 같다.
(자료형 뒤에 붙는 숫자는 몇 비트 크기인지를 의미한다.)

* 부호가 있는 정수 int(8, 16, 32, 64)
* 부호가 없는 정수 uint(8, 16, 32, 54)
* 실수 float(16, 32, 64, 128)
* 복소수 complex(64, 128, 256)
* 불리언 bool
* 문자열 string
* 파이썬 오브젝트 object
* 유니코드 unicode_
</pre>

#### 2-1. np.zeros(), np.ones(), np.arange() 함수
<pre>
numpy에서 array를 정의할 때 사용되는 함수들이다.
아래 실습을 통해 각각이 어떻게 다른지 살펴본다.
</pre>



In [0]:
# np.zeros() 함수는 인자로 받는 크기만큼, 모든 요소가 0인 array를 만든다.
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [0]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [0]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [0]:
# np.arange() 함수는 인자로 받는 값 만큼 1씩 증가하는 1차원 array를 만든다.
# 이때 하나의 인자만 입력하면 0 ~ 입력한 인자, 값 만큼의 크기를 가진다.
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 3.Array 연산
<pre>
기본적으로 numpy 에서 연산을 할 때는 크기가 서로 동일한 array 끼리 연산이 진행된다.
이 때 같은 위치에 있는 요소들 끼리 연산이 진행된다.

In [131]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[10,11,12],[13,14,15]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [132]:
arr2

array([[10, 11, 12],
       [13, 14, 15]])

In [0]:
# 3-1. array 덧셈
arr1+arr2

array([[11, 13, 15],
       [17, 19, 21]])

In [0]:
# 3-2. array 뺄셈
arr1-arr2

array([[-9, -9, -9],
       [-9, -9, -9]])

In [0]:
# 3-3. array 곱셈
# 주의하자.
# 행렬의 곱처럼 곱셈이 진행되는 것이 아니라 각 요소별로 곱셈이 진행된다.
arr1*arr2


array([[10, 22, 36],
       [52, 70, 90]])

In [0]:
# 3-4. array 나눗셈
arr1/arr2

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

In [0]:
# 3-5.array의 브로드 캐스트
# 위에서는 array가 같은 크기를 가져야 서로 연산이 가능하다고 했지만,
# numpy에서는 브로드캐스트라는 기능을 제공한다.
# 브로드캐스트란, 서로 크기가 다른 array가 연산이 가능하게끔 하는 것이다.

In [0]:
arr3=np.array([10,11,12])
print(arr3)

[10 11 12]


In [0]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
arr3

array([10, 11, 12])

In [0]:
arr1+arr3

array([[11, 13, 15],
       [14, 16, 18]])

In [0]:
arr1*arr3

array([[10, 22, 36],
       [40, 55, 72]])

In [0]:
arr1*4

array([[ 4,  8, 12],
       [16, 20, 24]])

In [0]:
# 요소에 대해 제곱처리
arr1**3

array([[  1,   8,  27],
       [ 64, 125, 216]])

In [0]:
# 위와 같이 서로 크기가 다른 arr1과 arr3의 연산이 가능하다.
# 연산 결과를 살펴보면 arr3이 [10,11,12] 에서 [[10,11,12],[10,11,12]]로 확장되어
# 계산되었음을 알 수 있다.
# 동일한 방식으로 하나의 array에 스칼라 연산도 가능하다.

In [0]:
# 4. Array 인덱싱
# numpy에서 사용되는 인덱싱은 기본적으로 python 인덱싱과 동일하다.
# 이 때, python에서와 같이 1번째로 시작하는 것이 아니라 0번째로 시작 하는 것.
# 주의!

In [133]:
arr1=np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
# 0번째 인덱스 요소
arr1[0]

0

In [134]:
# 3번째 인덱스 요소
arr1[3]

3

In [0]:
# 3번째 요소부터 8번째 요소
arr1[2:8]

array([2, 3, 4, 5, 6, 7])

In [0]:
arr1[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [137]:
# 물론 1차원이 아닌 그 이상의 차원에서도 인덱싱이 가능하다.
arr2=np.array([[1,2,3],
               [4,5,6],
               [7,8,9],
               [10,11,12]])
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [0]:
# 2차원의 array에서 인덱싱을 하기 위해서는 2개의 인자를 입력해야 한다.
arr2[0,0]


1

In [0]:
arr2[1,2]

6

In [138]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [139]:
# 2행의 모든 요소 꺼내기
arr2[1]

array([4, 5, 6])

In [140]:
# 2행의 3번째 요소 꺼내기
arr2[1,2]

6

In [141]:
# 모든 열의 3번째 요소 꺼내기
arr2[:,2]

array([ 3,  6,  9, 12])

In [144]:
arr2[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [145]:
arr2[2]

array([7, 8, 9])

In [0]:
# 5. Array boolean 인덱싱(마스크)
# 위에서 이용한 다차원의 인덱싱을 응용하여 boolean 인덱싱을 할 수 있다.
# 해당 기능은 주로 마스크라고 이야기하는데,
# boolean 인덱싱을 통해 만들어 낸 array를 통해
# 우리가 원하는 행 또는 열의 값만 뽑아낼 수 있다.
# 즉 마스크처럼 우리가 가리고 싶은 부분은 가리고, 원하는 요소만 꺼낼 수 있다.

In [0]:
names = np.array(['lee', 'park', 'kim', 'john', 'lee', 
                  'john', 'park', 'lee'])


In [147]:
names

array(['lee', 'park', 'kim', 'john', 'lee', 'john', 'park', 'lee'],
      dtype='<U4')

In [148]:
names.shape

(8,)

In [0]:
# 아래에서 사용되는 np.random.randn() 함수는 기대값이 0이고,
# 표준 편차가 1인 가우시안 정규분포를 따르는 난수를 발생시키는 함수이다.
# 이 외에도 0~1의 난수를 발생시키는 np.random.rand() 함수도 존재한다.
data = np.random.randn(8,4)
data

array([[-0.09022291, -0.01571907, -0.03666051,  0.34261947],
       [-0.73306485, -1.08080526, -1.18447714,  1.32804414],
       [ 0.32754564, -0.74285558, -0.36386716,  0.09572767],
       [-2.0448336 , -1.5454833 , -2.2549455 ,  1.11180166],
       [-1.14126963, -0.03886994,  0.32977399, -1.5347043 ],
       [ 0.20578172,  0.2129015 , -1.73957774, -0.88646647],
       [ 0.07792297, -0.52834212, -0.86560322,  0.09276499],
       [-1.43943649, -1.0792594 ,  0.36356394,  0.64056382]])

In [0]:
data.shape

(8, 4)

In [0]:
# 위와 같은 names와 data라는 array가 있다.
# 이 때, names의 각 요소가 data의 각 행과 연결된다고 가정해보자.
# 그리고 이 때, names가 lee인 행의 data만 보고 싶을 때 다음과 같이 마스크를 사용.

In [0]:
names

array(['lee', 'park', 'kim', 'john', 'lee', 'john', 'park', 'lee'],
      dtype='<U4')

In [0]:
# 요소가 lee인 항목에 대한 mask 생성 true false 값
names_lee_mask = (names =='lee')
names_lee_mask

array([ True, False, False, False,  True, False, False,  True])

In [0]:
data[names_lee_mask,:]

array([[-0.09022291, -0.01571907, -0.03666051,  0.34261947],
       [-1.14126963, -0.03886994,  0.32977399, -1.5347043 ],
       [-1.43943649, -1.0792594 ,  0.36356394,  0.64056382]])

In [0]:
# 위의 결과를 보면, 요소가 lee인 것은 0번째, 4번째, 7번째 이므로
# data에서 0,4,7행의 모든 요소를 꺼내와야 한다.
# 이를 위해 요소가 lee인 것에 대한 boolean 값을 가지는 mask를 만들었고,
# 마스크를 인덱싱에 응용하여 data의 0,4,7행을 꺼냈다.

In [0]:
# 요소가 kim인 행의 데이터만 꺼내기
names_kim_mask = (names =='kim')
names_kim_mask
data[names_kim_mask,:]

array([[ 0.32754564, -0.74285558, -0.36386716,  0.09572767]])

In [0]:
# 논리 연산을 응용하여, 요소가 kim 또는 park 인 행의 데이터만 꺼내기

data[(names=='kim') | (names=='lee'),:]

array([[-0.09022291, -0.01571907, -0.03666051,  0.34261947],
       [ 0.32754564, -0.74285558, -0.36386716,  0.09572767],
       [-1.14126963, -0.03886994,  0.32977399, -1.5347043 ],
       [-1.43943649, -1.0792594 ,  0.36356394,  0.64056382]])

In [0]:
# 물론 data array 자체적으로도 마스크를 만들고, 이를 응용하여 인덱싱이 가능하다.
# data array에서 3번째 열의 값이 0보다 작은 행을 구해보자.

data[:2]

array([[-0.09022291, -0.01571907, -0.03666051,  0.34261947],
       [-0.73306485, -1.08080526, -1.18447714,  1.32804414]])

In [0]:
# 먼저 마스크를 만든다.
# data array에서 3번째 열이 0보다 작은 요소의 boolean 값은 다음과 같다.

data[:,2]<0

array([ True,  True,  True,  True, False,  True,  True, False])

In [0]:
# 위에서 만든 마스크를 이용하여 0번째 열의 값이 0보다 작은 행을 구한다.
data[data[:,2]<0,:]

array([[-0.09022291, -0.01571907, -0.03666051,  0.34261947],
       [-0.73306485, -1.08080526, -1.18447714,  1.32804414],
       [ 0.32754564, -0.74285558, -0.36386716,  0.09572767],
       [-2.0448336 , -1.5454833 , -2.2549455 ,  1.11180166],
       [ 0.20578172,  0.2129015 , -1.73957774, -0.88646647],
       [ 0.07792297, -0.52834212, -0.86560322,  0.09276499]])

In [0]:
# 이를 통해 특정 위치에만 우리가 원하는 값을 대입할 수 있다.
# 위에서 얻은, 0번째 열의 값이 0보다 작은 행의
# 2,3번째 열의 값에 0을 대입해보자.

In [0]:
# 3번째 열의 값이 0보다 작은 행의 2,3 번째 열 값
data[data[:,2]<0,1:3 ] =0
data

array([[-0.09022291,  0.        ,  0.        ,  0.34261947],
       [-0.73306485,  0.        ,  0.        ,  1.32804414],
       [ 0.32754564,  0.        ,  0.        ,  0.09572767],
       [-2.0448336 ,  0.        ,  0.        ,  1.11180166],
       [-1.14126963, -0.03886994,  0.32977399, -1.5347043 ],
       [ 0.20578172,  0.        ,  0.        , -0.88646647],
       [ 0.07792297,  0.        ,  0.        ,  0.09276499],
       [-1.43943649, -1.0792594 ,  0.36356394,  0.64056382]])

In [0]:
# 6. Numpy 함수
# numpy에서는 array에 적용되는 다양한 함수가 있다.

In [0]:
# 6-1. 하나의 array에 적용되는 함수
arr1=np.random.randn(5,3)
arr1

array([[ 1.16727259,  1.61546802, -0.02421065],
       [-0.12746447,  0.67123415, -0.14296083],
       [-0.04372709,  0.64634846, -2.16459875],
       [ 1.45254653,  0.03248493,  0.89455093],
       [-0.22003546, -0.49542293, -0.81905406]])

In [0]:
# 각 성분의 절대값 계산하기
np.abs(arr1)

array([[1.16727259, 1.61546802, 0.02421065],
       [0.12746447, 0.67123415, 0.14296083],
       [0.04372709, 0.64634846, 2.16459875],
       [1.45254653, 0.03248493, 0.89455093],
       [0.22003546, 0.49542293, 0.81905406]])

In [0]:
# 각 성분의 제곱근 계산하기 ( == array ** 0.5)
np.sqrt(arr1)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([[1.0804039 , 1.27101063,        nan],
       [       nan, 0.81928881,        nan],
       [       nan, 0.803958  ,        nan],
       [1.20521638, 0.18023577, 0.94580702],
       [       nan,        nan,        nan]])

In [0]:
# 각 성분의 제곱 계산하기
np.square(arr1)

array([[1.36252529e+00, 2.60973694e+00, 5.86155510e-04],
       [1.62471899e-02, 4.50555282e-01, 2.04377993e-02],
       [1.91205802e-03, 4.17766334e-01, 4.68548777e+00],
       [2.10989141e+00, 1.05527079e-03, 8.00221363e-01],
       [4.84156058e-02, 2.45443881e-01, 6.70849561e-01]])

In [0]:
# 각 성분을 무리수 e의 지수로 삼은 값을 계산하기


In [0]:
# 각 성분을 자연로그, 상용로그, 밑이 2인 로그를 씌운 값을 계산하기


In [0]:
# 각 성분의 부호 계산하기(+인 경우 1, -인 경우 -1, 0인 경우 0)


In [0]:
# 각 성분의 소수 첫 번째 자리에서 올림한 값을 계산하기


In [0]:
# 각 성분의 소수 첫 번째 자리에서 내림한 값을 계산하기


In [0]:
# 각 성분이 NaN인 경우 True를, 아닌 경우 False를 반환하기
np.isnan(arr1)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [0]:
# 각 성분이 무한대인 경우 True를, 아닌 경우 False를 반환하기


In [0]:
# 각 성분에 대해 삼각함수 값을 계산하기(cos, cosh, sin, sinh, tan, tanh)


In [0]:
# 6-2. 두 개의 array에 적용되는 함수


In [0]:
# 두 개의 array에 대해 동일한 위치의 성분끼리 연산 값을 계산하기
# (dd, subtract, multiply, divide)


In [0]:
# 두 개의 array에 대해 동일한 위치의 성분끼리 비교하여 최대값 또는
# 최소값 계산하기(maximum, minimum)


In [0]:
# 6-3. 통계 함수
# 통계 함수를 통해 array의 합이나 평균 등을 구할 때,
# 추가로 axis라는 인자에 대한 값을 지정하여
# 열 또는 행의 합 또는 평균 등을 구할 수 있다.

In [0]:
# 전체 성분의 합을 계산
np.sum(arr1)

2.4424313598861636

In [0]:
# 열 간의 합을 계산
np.sum(arr1, axis=1)

In [0]:
# 행 간의 합을 계산
np.sum(arr1,axis=0)

array([ 2.2285921 ,  2.47011263, -2.25627337])

In [0]:
# 전체 성분의 평균을 계산
np.mean(arr1)

0.16282875732574423

In [0]:
# 행 간의 평균을 계산


In [0]:
# 전체 성분의 표준편차, 분산, 최소값, 최대값 계산
# (std, var, min, max)


In [0]:
# 전체 성분의 최소값, 최대값이 위치한 인덱스를 반환
# (argmin, argmax)
np.argmin(arr1)

8

In [0]:
np.argmax(arr1)

1

In [0]:
# 맨 처음 성분부터 각 성분까지의 누적합 또는 누적곱을 계산
# (cumsum, cumprod)
np.cumsum(arr1,axis=1)

array([[ 1.16727259,  2.78274061,  2.75852996],
       [-0.12746447,  0.54376968,  0.40080885],
       [-0.04372709,  0.60262138, -1.56197738],
       [ 1.45254653,  1.48503146,  2.37958239],
       [-0.22003546, -0.7154584 , -1.53451246]])

In [0]:
# 6-4. 기타 함수

In [0]:
# 같은 행에 대해서 오름차순으로 정렬
np.sort(arr1,axis=0)

array([[-0.22003546, -0.49542293, -2.16459875],
       [-0.12746447,  0.03248493, -0.81905406],
       [-0.04372709,  0.64634846, -0.14296083],
       [ 1.16727259,  0.67123415, -0.02421065],
       [ 1.45254653,  1.61546802,  0.89455093]])

In [0]:
# 같은 행에 대해서 내림차순으로 정렬
np.sort(arr1,axis=0)[::-1]

array([[ 1.45254653,  1.61546802,  0.89455093],
       [ 1.16727259,  0.67123415, -0.02421065],
       [-0.04372709,  0.64634846, -0.14296083],
       [-0.12746447,  0.03248493, -0.81905406],
       [-0.22003546, -0.49542293, -2.16459875]])

In [0]:
# 행 방향으로 오름차순으로 정렬
